export const ADD_DOMAIN_NAME = "ADD_DOMAIN_NAME";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_LOGIN = "CHANGE_LOGIN";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const CHANGE_REFRESH_STATE = "CHANGE_REFRESH_STATE";
