name: Coopmo Test (JAVA CI + MYSQL)

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Run Docker-Compose
      run: docker-compose up -d