name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup MySQL
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'coopmo_db'
        mysql root password: 'coopmopass'
        mysql user: 'coopmo'
        mysql password: 'coopmopass'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
